<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Phalcon Config</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>

<body>
    <div class="container">
        <h3>App Name </h3>
        <b><?php echo $app; ?></b>
        <h3>Database Host name</h3>
        <b><?php echo $dbhost; ?></b>
    </div>
</body>
</html>
